global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_targets:
      - targets: ['localhost:9090']

  - job_name: 'node'
    scrape_interval: 5s
    static_targets:
      - targets: ['localhost:9100']
# remote_write:
#   - url: '<Your Prometheus remote_write endpoint>'
#     basic_auth:
#       username: '<Your Grafana Username>'
#       password: '<Your Grafana API key>'